
Database:
  # Modos disponíveis: HIKARICP, MYSQL e SQLITE.
  Mode: SQLITE
  Host: localhost
  Port: 3306
  Database: SOPlugins
  Username: 'Username'
  Password: 'Password'
  # Caso dê algum erro ao tentar conectar com o MySQL ou HIKARI, coloque 'com.mysql.cj.jdbc.Driver' no driver!
  MySQLDriver: 'com.mysql.jdbc.Driver'
  HikariConfiguration:
    PoolName: 'MiyukiSystemPool'
    MiniumIdle: 10
    MaximumPoolSize: 10
    ConnectionTimeout: 30000
    CachePrepStmts: true
    PrepStmtCacheSize: 250
    PrepStmtCacheSqlLimit: 2048
    UseServerPrepStmts: true
    UseLocalSessionState: true
    RewriteBatchedStatements: true
    CacheResultSetMetadata: true
    CacheServerConfiguration: true
    ElideSetAutoCommits: true
    MaintainTimeStats: false

# Se deixar true, toda vez q o player entrar, ele vai ser teleportado pro spawn invez de
# sua ultima localização.
TeleportSpawn: true

# Tempo para expirar o TPA (em segundos)
TpaExpire: 30

# Lixeiro

TrashSize: 54
TrashTitleMenu: 'Lixeiro'


# true -> bloqueado
# false -> não bloqueado

# Para pesquisar, veja aqui na lista abaixo os bloqueadores e de um CTRL+F para pesquisar.
# Exemplo: CTRL + F, LeavesDecay

Blockers:
  # Bloqueia de transformar a água em gelo.
  FreezeWater: true
  # Bloqueia de cair no void (teleporta pro spawn).
  FallIntoVoid: true
  # Bloqueia de criar portal do nether.
  CreatePortal: true
  # Bloqueia dos mobs pegarem fogo para o sol.
  MobsCatchFire: true
  # Bloqueia das folhas cairem.
  LeavesDecay: true
  # Bloqueia das bigornas cairem.
  AnvilDecay: true
  # Cancela a chuva quando comecar.
  RainCancel: true
  # Cancela o player de entrar na cama.
  Sleep: true

# Reparar

RepairBlockedNBTs: # Deixe com "[]" para não bloquear nenhum.
  - 'NBT1'
  - 'NBT2'
RepairBlockedItems: # Deixe com "[]" para não bloquear nenhum.
  - 'DIAMOND_PICKAXE'

Motd: # Lembrando que se deixar vaziu ele fica o default da server.properties. (Ignora o MaxPlayers também!)
  # Motd quando está em WHITELIST (Use \n para pular linha)
  WhitelistMotd: ''
  # Jogadores máximos quando está em WHITELIST. (Apenas estático)
  WhitelistMaxPlayers: 1
  # Motd normal (Use \n para pular linha);
  NormalMotd: ''
  # Jogadores máximos com a motd normal. (Apenas estático)
  NormalMaxPlayers: 200

BlockedNicks:
  - 'teste1'
  - 'teste2'

BlockedCommands: # Use "/".
  - '/teste1'
  - '/teste2'

# Lista de materiais 1.8: https://helpch.at/docs/1.8/org/bukkit/Material.html
# Lista de materiais 1.12:
BlockedCrafts:


