# true -> bloqueado
# false -> não bloqueado

# Bloquear de transformar a agua em gelo.
FreezeWater: true
# Bloquear de cair no void.
FallIntoVoid: true
# Bloquear de criar portal.
CreatePortal: true
# Bloquear de mobs pegarem fogo ao sol
MobsCatchFire: true
# Bloquear das folhas cairem
LeavesDecay: true
# Bloquear as bigornas cairem
AnvilDecay: true
# Bloquear a chuva
RainCancel: true

