#
# Lista de materiais: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#
# true -> sim
# false -> não
#
# Para pesquisar, veja aqui na lista abaixo os bloqueadores e de um CTRL+F para pesquisar.
# Exemplo: CTRL + F, LeavesDecay

Database:
  # Modos disponíveis: H2, MARIADB, MYSQL e SQLITE.
  Mode: H2
  Host: localhost
  Port: 3306
  Database: MiyukiSystem
  Username: 'Username'
  Password: 'Password'
  MySQLConfiguration:
    PoolName: 'MiyukiSystemPool'
    MiniumIdle: 10
    MaximumPoolSize: 10
    ConnectionTimeout: 30000
    CachePrepStmts: true
    PrepStmtCacheSize: 250
    PrepStmtCacheSqlLimit: 2048
    UseServerPrepStmts: true
    UseLocalSessionState: true
    RewriteBatchedStatements: true
    CacheResultSetMetadata: true
    CacheServerConfiguration: true
    ElideSetAutoCommits: true
    MaintainTimeStats: false

# Se deixar true, toda vez q o player entrar, ele vai ser teleportado pro spawn invez de
# sua ultima localização.
TeleportSpawn: true

# Tempo para expirar o TPA (em segundos)
TpaExpire: 30

# Lixeiro

TrashSize: 54
TrashTitleMenu: 'Lixeiro'

Blockers:
  # Bloqueia de transformar a água em gelo.
  FreezeWater: true
  # Bloqueia de cair no void (teleporta pro spawn).
  FallIntoVoid: true
  # Bloqueia de criar portal do nether.
  CreatePortal: true
  # Bloqueia dos mobs pegarem fogo para o sol.
  MobsCatchFire: true
  # Bloqueia das folhas cairem.
  LeavesDecay: true
  # Bloqueia das bigornas cairem.
  AnvilDecay: true
  # Cancela a chuva quando comecar.
  RainCancel: true
  # Cancela o player de entrar na cama.
  Sleep: true
  # Cancela de derreter o gelo e a neve.
  Melt: true
  # Cancela a explosão dos itens.
  ItemExplosion: true
  # Cancela de entrar em portais. Se tiver true = bloqueia.
  Portal:
    Nether: true
    End: true
  # Cancela a fome. Se tiver true = não tem mais fome.
  Feed: true
  # Cancela a mensagem de morte.
  DeathMessage: true
  # Bloqueia do jogador entrar em veículos.
  PlayerGetIntoVehicles: false
  # Bloqueia de entidades (MOBS) entrarem em veículos.
  EntityGetIntoVehicles: true

# Reparar

RepairBlockedNBTs: # Deixe com "[]" para não bloquear nenhum.
  - 'NBT1'
  - 'NBT2'
RepairBlockedItems: # Deixe com "[]" para não bloquear nenhum.
  - 'DIAMOND_PICKAXE'

Motd: # Lembrando que se deixar vaziu ele fica o default da server.properties. (Ignora o MaxPlayers também!)
  # Motd quando está em WHITELIST (Use \n para pular linha)
  WhitelistMotd: ''
  # Jogadores máximos quando está em WHITELIST. (Apenas estático)
  WhitelistMaxPlayers: 1
  # Motd normal (Use \n para pular linha);
  NormalMotd: ''
  # Jogadores máximos com a motd normal. (Apenas estático)
  NormalMaxPlayers: 200

BlockedNicks:
  - 'teste1'
  - 'teste2'

BlockedCommands: # Use "/".
  - '/teste1'
  - '/teste2'

BlockedCrafts:


