main: miyukisystem.Main
version: 1.0.0-SNAPSHOT
name: MiyukiSystem
load: POSTWORLD
authors: [RUSH, SOekd, mattnicee7, Kroxy_]
website: github.com/SOekd/MiyukiSystem
softdepend: [Legendchat, mcMMO, MassiveCore, Factions, Vault]
